In [17]:
import pandas as pd

df = pd.read_csv('../data/factory_glass_2016.csv', index_col= 0, encoding= 'cp949')
df.head()

process_nm = list(df.columns)
process_nm = process_nm[:-14] # 마지막 공정명 14개 제외
process_nm[:5]

process_df = df.iloc[:, :-14]
process_df.head()

,LIFT.OUT.ROL.MTR.M1.SPD.1WSI40101,LIFT.OUT.ROL.MTR.M2.SPD.1WSI40102,LIFT.OUT.ROL.MTR.M3.SPD.1WSI40103,LEHR.DRV.MTR..M4.1.SPD.1WSI40104,LEHR.DRV.MTR..M4.2.SPD.1WSI40105,LEHR.DRV.MTR..M5.1.SPD.1WSI40106,LEHR.DRV.MTR..M5.2.SPD.1WSI40107,LEHR.DRV.MTR..M6.1.SPD.1WSI40108,LEHR.DRV.MTR..M6.2.SPD.1WSI40109,LEHR.DRV.MTR..M7.1.SPD.1WSI40110,...,S_C4_RET_L,S_C4_RET_R,S_RET_F_L,S_RET_F_R,STD_U_L,STD_U_R,STD_L_L,STD_L_R,STD_GLS_L,STD_GLS_R
dat...date.name.,,,,,,,,,,,,,,,,,,,,,
2016-01-01 07,-1.772682,-1.713219,-1.734851,-1.590051,-1.636293,-1.575213,-1.636293,-1.548119,-1.824581,-1.548119,...,-0.365598,-0.659319,-1.963403,-1.621407,0.523950,1.951349,2.248106,2.767676,3.012706,3.069007
2016-01-01 08,-1.772682,-1.713219,-1.734851,-1.590051,-1.636293,-1.575213,-1.636293,-1.548119,-1.824581,-1.548119,...,-0.348979,-0.560103,-1.978936,-1.810022,0.566521,2.010125,2.364418,2.842630,3.022998,3.069274
2016-01-01 09,-1.772682,-1.713219,-1.734851,-1.590051,-1.636293,-1.575213,-1.636293,-1.548119,-1.824581,-1.548119,...,-0.456071,-0.644073,-1.878611,-1.742395,0.545936,2.002820,2.397034,2.817728,2.936967,2.969952
2016-01-01 10,-1.772682,-1.713219,-1.734851,-1.590051,-1.636293,-1.575213,-1.636293,-1.548119,-1.824581,-1.548119,...,-0.463717,-0.585540,-1.863727,-1.845004,0.549254,2.047995,2.399854,2.810619,2.876398,2.914596
2016-01-01 11,-1.772682,-1.713219,-1.734851,-1.590051,-1.636293,-1.575213,-1.636293,-1.548119,-1.824581,-1.548119,...,-0.421995,-0.580300,-1.903504,-1.781370,0.610913,2.101178,2.379341,2.797094,2.858177,2.873929

In [18]:
process_df.iloc[:5, -14:] # 일자 + 00~23까지의 라인 > 총 24개의 라인 예상이 아니고 > 1시간마다 측정한 결과인가보다

,S_AB11_AB7_L,S_AB11_AB7_R,S_AB7_C4_L,S_AB7_C4_R,S_C4_RET_L,S_C4_RET_R,S_RET_F_L,S_RET_F_R,STD_U_L,STD_U_R,STD_L_L,STD_L_R,STD_GLS_L,STD_GLS_R
dat...date.name.,,,,,,,,,,,,,,
2016-01-01 07,-1.192642,-1.134471,2.599429,2.690433,-0.365598,-0.659319,-1.963403,-1.621407,0.523950,1.951349,2.248106,2.767676,3.012706,3.069007
2016-01-01 08,-1.109125,-1.042269,2.588703,2.654307,-0.348979,-0.560103,-1.978936,-1.810022,0.566521,2.010125,2.364418,2.842630,3.022998,3.069274
2016-01-01 09,-0.986580,-0.928583,2.550175,2.606185,-0.456071,-0.644073,-1.878611,-1.742395,0.545936,2.002820,2.397034,2.817728,2.936967,2.969952
2016-01-01 10,-0.885353,-0.860442,2.518261,2.551495,-0.463717,-0.585540,-1.863727,-1.845004,0.549254,2.047995,2.399854,2.810619,2.876398,2.914596
2016-01-01 11,-0.852229,-0.821249,2.521009,2.541783,-0.421995,-0.580300,-1.903504,-1.781370,0.610913,2.101178,2.379341,2.797094,2.858177,2.873929

In [19]:
original_columns = process_df.columns.tolist()
original_process_df = pd.Series(original_columns).str.split(r'[._]', expand=True)
original_process_df.head()
# original_process_df.to_csv('../data/original_process_nm.csv', index= False, header= False)

      0    1    2    3   4    5          6          7     8     9
0  LIFT  OUT  ROL  MTR  M1  SPD  1WSI40101       None  None  None
1  LIFT  OUT  ROL  MTR  M2  SPD  1WSI40102       None  None  None
2  LIFT  OUT  ROL  MTR  M3  SPD  1WSI40103       None  None  None
3  LEHR  DRV  MTR       M4    1        SPD  1WSI40104  None  None
4  LEHR  DRV  MTR       M4    2        SPD  1WSI40105  None  None

> ### 공정명 정규화

1. 용어 통일

SPEED > SPD    
MOTOR > MTR   
DRIVE > DRV

In [20]:
norm_process_df = process_df.copy()

In [21]:
def unify_process_names(name):
    name = name.replace('SPEED', 'SPD')
    name = name.replace('MOTOR', 'MTR')
    name = name.replace('DRIVE', 'DRV')
    return name

# 적용 예시: process_df 컬럼명 변경
norm_process_df.columns = [unify_process_names(col) for col in norm_process_df.columns]
print(norm_process_df.columns)

Index(['LIFT.OUT.ROL.MTR.M1.SPD.1WSI40101',
       'LIFT.OUT.ROL.MTR.M2.SPD.1WSI40102',
       'LIFT.OUT.ROL.MTR.M3.SPD.1WSI40103', 'LEHR.DRV.MTR..M4.1.SPD.1WSI40104',
       'LEHR.DRV.MTR..M4.2.SPD.1WSI40105', 'LEHR.DRV.MTR..M5.1.SPD.1WSI40106',
       'LEHR.DRV.MTR..M5.2.SPD.1WSI40107', 'LEHR.DRV.MTR..M6.1.SPD.1WSI40108',
       'LEHR.DRV.MTR..M6.2.SPD.1WSI40109', 'LEHR.DRV.MTR..M7.1.SPD.1WSI40110',
       ...
       'S_C4_RET_L', 'S_C4_RET_R', 'S_RET_F_L', 'S_RET_F_R', 'STD_U_L',
       'STD_U_R', 'STD_L_L', 'STD_L_R', 'STD_GLS_L', 'STD_GLS_R'],
      dtype='object', length=826)

2. 점(.) 삽입 - 영어 + 숫자 + (. 삽입) +  영어

Z35TMP > Z35.TMP

In [22]:
import re

def insert_dot_between_zone_and_suffix(s):
    # 1. 영문 + 숫자 + 영문 → 점 삽입 (예: ZONE10PRESSURE → ZONE.PRESSURE)
    s = re.sub(r'([A-Za-z]+)\d+([A-Za-z]{2,})', r'\1.\2', s)
    # 2. 숫자 + 영문 → 점 삽입 (예: 8BAY → .BAY)
    s = re.sub(r'\b\d+([A-Za-z]{2,})\b', r'.\1', s)
    return s

norm_process_df.columns = [insert_dot_between_zone_and_suffix(col) for col in norm_process_df.columns]

print(norm_process_df.columns)

# norm_process_df.to_csv('../data/norm_factory_glass_2016.csv', index=False)

Index(['LIFT.OUT.ROL.MTR.M1.SPD.1WSI40101',
       'LIFT.OUT.ROL.MTR.M2.SPD.1WSI40102',
       'LIFT.OUT.ROL.MTR.M3.SPD.1WSI40103', 'LEHR.DRV.MTR..M4.1.SPD.1WSI40104',
       'LEHR.DRV.MTR..M4.2.SPD.1WSI40105', 'LEHR.DRV.MTR..M5.1.SPD.1WSI40106',
       'LEHR.DRV.MTR..M5.2.SPD.1WSI40107', 'LEHR.DRV.MTR..M6.1.SPD.1WSI40108',
       'LEHR.DRV.MTR..M6.2.SPD.1WSI40109', 'LEHR.DRV.MTR..M7.1.SPD.1WSI40110',
       ...
       'S_C4_RET_L', 'S_C4_RET_R', 'S_RET_F_L', 'S_RET_F_R', 'STD_U_L',
       'STD_U_R', 'STD_L_L', 'STD_L_R', 'STD_GLS_L', 'STD_GLS_R'],
      dtype='object', length=826)

> ### 피쳐 추출

1. 공정명 정리

 1) 공정명 정리 : 형식 = 1 + 알파벳(2~5자) + 숫자(2~5자)          
- 센서명 제거   
- 위치 키워드 + 숫자 > 숫자 제거   
- 접미사 제거(.PV, .CPV)
          
 2) 센서명 제거한 공정명 매핑을 위해 저장
             
 3) 센서명 제거 후 _ 나 .으로 구분해서 DF 저장 
   
 4) 공정명 확인

In [16]:
norm_process_df.columns[62]

'DAMP.POSITION.BAY.CTRL'

In [24]:
import re

# 센서 ID 및 접미사 제거용 정규표현식
sensor_pattern = re.compile(
    r'(1[A-Z]{2,5}\d{5}[A-Z]*|WOS\d+)',  # 센서 ID
    re.IGNORECASE
)

def clean_column_name(col):
    # 1. 공백, 언더바 → 점으로 정규화
    col = col.replace(' ', '.').replace('_', '.')
    col = re.sub(r'\.+', '.', col).strip('.')
    # 2. 센서 ID 제거
    col = sensor_pattern.sub('', col)
    col = re.sub(r'\.+', '.', col).strip('.')
    # 3. 위치 키워드 + 숫자 → 숫자 제거
    col = re.sub(r'\b(ZONE|Zone|POSITION|M|Z|BAY|SECT|AB|C)(\d+)', r'\1', col, flags=re.IGNORECASE)    
    col = re.sub(r'\.+', '.', col).strip('.')    
    # 4. .PV, .CPV, .숫자 제거 (접미사)
    col = re.sub(r'\.(PV|CPV|\d+)$', '', col, flags=re.IGNORECASE)
    # 5. 숫자 정리
    col = re.sub(r'\b\d+\b', '', col)
    col = re.sub(r'\.+', '.', col).strip('.')    
    return col

# 분리 함수
def split_and_align(col, max_len):
    parts = re.split(r'[._]', col)
    return [None] * (max_len - len(parts)) + parts  # 오른쪽 정렬

# 원본 컬럼 리스트 예시 (process_df.columns 사용 시 적용)
original_columns = norm_process_df.columns  # 또는 샘플 리스트 직접 넣기

# 정제 및 분할
sensor_cleaned = [clean_column_name(col) for col in original_columns] 
split_cleaned = [re.split(r'[._]', c) for c in sensor_cleaned]
max_len = max(len(x) for x in split_cleaned)

# 우측 정렬
aligned = [split_and_align(c, max_len) for c in sensor_cleaned]

cleaned_process_df = pd.DataFrame(sensor_cleaned)
cleaned_process_df.to_csv('../data/original_process_nm_split.csv', index= False, header= False)

split_process_df = pd.DataFrame(aligned)
split_process_df.to_csv('../data/process_nm_split.csv', index=False, header=False)

# 마지막에 PV, CPV, 1, PV.1, CT
# PV : process value
# CPV : Calculated Process Vale(계산된 공정값 / 보정된 센서값)
# PV.1 : 센서가 여러 개의 채널값을 가질 때(이중 센서, 백업 센서)
# CT : Control Target으로 제어 목표값 / 지령값

# 1TI30101.CT : 이 온도 센서가 따라야 하는 설정 목표값일 수 있음

unique_process = set(sensor_cleaned)
print(unique_process)
# len(unique_process) # 722

{'DB.N2.SCREEN.FLOW.RIGHT', 'ROOF.HT.BAY.TOTAL.PWR.1CLBAY7', 'SPOUT.LEFT.BOS.UPSTREAM', 'ROOF.HT.BAY.TOTAL.PWR.1CLBAY6', 'D.AB.R.UL', 'DB.HEAT.BTM.LEFT.TMP', 'DROSSBOX.N2.SCN.L', 'ROOF.HT.BAY.TOTAL.PWR.1CLBAY2', 'ROOF.HEATING.Zone.PV', 'le.re.btm.dn', 'S.C.C.U.R', 'TMP.GLASS.ZONE.AB.L1', 'S.C.RET.L', 'r.n.glass', 'ATM.N2.H2.함유율', 'X.BAY.RIGHT.PRESSURE.CLBAY.RIGHT', 'BATH.AMBIENT.BAY.LEFT', 'TMP.GLASS.ZONE.F.E2', 'TMP.GLASS.ZONE.AB.GB', 'S.AB.C.U.R', 'TMP.GLASS.ZONE.AB.L3', 'TMP.GLASS.ZONE.AB.L2', 'HOOD.N2.TOP.HEATER.L', 'UPPER.RET.Z.TMP', 'ATM.FLOW.SECT.N2.PV', 'TMP.GLASS.ZONE.AB.E1', 'c.btm.up.dn', 'S.AB.AB.U.L', 'S.AB.AB.L', 'r.top.n.mean', 'S.AB.AB.L.L', 'TMP.GLASS.Z.RET.E3', 'TMP.GLASS.ZONE.F.E3', 'D.AB.U.LR', 'cluster', 'SPOUT.RIGHT.TOP', 'D.GLS.F.LR', 'ROOF.HT.BAY.TOTAL.PWR.1CLBAYTOT', 'LOR.L.Axis', 'STD.L.L', 'LIFT.OUT.ROL.MTR.M.SPD', 'TMP.GLASS.ZONE.F.E5', 'N2.TO.EA1313A', 'DRV.MTR.M.SPD', 'DDP.RIGHT.N2.H2', 'DB.N2.SCREEN.FLOW.RIGHT.PV', 'l.top.n.mean', 'S.AB.C.R', 'DROSS.BOX.N2.BTM.HT.R', 'STD.U.L', 'S.AB.C.L.L', 'ATM.FLOW.SECT.N2.H2', 'RET.AMBIANT.RIGHT.TMP', 'TMP.GLASS.ZONE.AB.L5', 'LEHR.DRV.MTR.M.CUR', 'CASHING.HOT.AIR.TMP', 'Left.edge', 'DB.BTM.UP.STM.TC.C', 'LEHR.AB.PRESS', 'SPOUT.RIGHT.UPSTREAM', 'ROOF.HEATING.Zone', 'l.r.top.n', 'TMP.GLASS.Z.RET.E5', 'DCS.Offset.RPM.M.PV', 'TMP.GLASS.ZONE.F.E4', 'DB.HEAT.TOP.TMP', 'S.C.C.L.R', 'SPOUT.LEFT.UPSTREAM', 'S.C.C.U.L', 'STD.GLS.R', 'l.r.glass', 'ROOF.HT.BAY.TOTAL.PWR.1CLBAY8', 'TMP.GLASS.ZONE.AB.E4', 'TMP.GLASS.ZONE.AB.L4', 'ATM.FLOW.SECT.N2.H2.PV', 'UPPER.C.Z.TMP', 'TMP.GLASS.CENTER.EXIT', 'TMP.GLASS.ZONE.C.E5', 'top', 'Gross.width', 'S.AB.C.L.R', 'TMP.GLASS.ZONE.AB.E5', 'N2.TO.HOOD.DOWN.STREAM', 'D.AB.L.UL', 'D.C.L.LR', 'DB.N2.SCREEN.FLOW.LEFT.PV', 'DAMP.POSITION.BAY.CTRL', 'X.BAY.LEFT.PRESSURE.CLBAY.LEFT', 'TMP.GLASS.ZONE.C.E2', 'DDP.LEFT.N2.H2', 'X.LEHR.O2.ANALYZER', 'TMP.TIN.BAY.LEFT', 'ROOF.HT.BAY.TOTAL.PWR.1CLBAY3', 'DAMP.POSITION.BAY.CTRL.PV', 'S.AB.C.U.L', 'SEC11.N2.PV', 'lc.rc.btm.dn', 'ROOF.HT.BAY.TOTAL.PWR.1CLBAY11', 'ML.Speed', 'D.GLS.RET.LR', 'UPPER.AB.Z.TMP', 'rc.btm.up.dn', 'l.r.tin.bay', 'DROSS.BOX.N2.BTM.HT.L', 'TMP.GLASS.Z.RET.E4', 'DROSS.BOX.N2.BTM.HT1.R', 'N2.TO.EA1315B', 'EXIT.LIP.PLATE.LEFT', 'DB.BTM.DN.STM.TC.LC', 'l.tin.bay', 'ATM.FLOW.SECT.N2', 'D.C.U.LR', 'BATH.AMBIENT.BAY.RIGHT', 'DCS.Offset.RPM.M', 're.btm.up.dn', 'S.AB.AB.R', 'E.L.DB.LEFT.N2.FLOW', 'RET.AMBIANT.LEFT.TMP', 'D.GLS.C.LR', 'DB.BTM.DN.STM.TC.C', 'CASHING.COLD.AIR.TMP', 'Ribbon.Speed', 'TMP.TIN.BAY.RIGHT', 'Right.edge', 'HOOD.N2.HEATER.R', 'S.C.C.L.L', 'S.AB.C.L', 'TMP.GLASS.Z.RET.E1', 'TMP.GLASS.LEFT.EXIT', 'LOR.R.Axis', 'S.C.RET.R', 'X.LEHR.SO2.ANALYZER', 'DROSS.BOX.PRESS', 'SEC11.N2', 'DB.BTM.UP.STM.TC.RC', 'TMP.GLASS.ZONE.C.E4', 'DB.BTM.DN.STM.TC.RE', 'E.L.DB.RIGHT.N2.FLOW', 'LOR.L.Hori', 'l.n.glass', 'SEC11.N2.H2.PV', 'DROSS.BOX.N2.BTM.HT1.L', 'SEC11.N2.H2', 'N2.TO.EA1315A', 'D.AB.L.LR', 'LOWER.C.Z.TMP', 'TMP.GLASS.ZONE.C.E3', 'LOWER.AB.Z.TMP', 'DB.BTM.UP.STM.TC.RE', 'S.RET.F.L', 'TMP.GLASS.BAY', 'S.RET.F.R', 'STD.GLS.L', 'ROOF.HT.BAY.TOTAL.PWR.1CLBAY5', 'S.AB.AB.U.R', 'DB.HEAT.TOP.TMP.CT', 'ROOF.HT.BAY.TOTAL.PWR.1CLBAY9', 'STD.L.R', 'ROOF.HT.BAY.TOTAL.PWR.1CLBAY4', 'DB.N2.SCREEN.FLOW.LEFT', 'X.PV', 'LIFT.OUT.ROL.MTR.M.CUR', 'SPOUT.RIGHT.BOTTOM', 'S.AB.AB.L.R', 'LEHR.DRV.MTR.M.SPD', 'DB.HEAT.BOTTOM', 'r.tin.bay', 'N2.TO.HOOD.UP.STREAM', 'X', 'TMP.GLASS.Z.RET.E2', 'DB.BTM.DN.STM.TC.LE', 'ROOF.HT.BAY.TOTAL.PWR.1CLBAY10', 'bay', 'bay.stream.var', 'D.GLS.AB.LR', 'D.C.L.UL', 'LOR.R.Hori', 'TMP.GLASS.ZONE.AB.E2', 'DB.BTM.DN.STM.TC.RC', 'EXIT.LIP.PLATE.RIGHT', 'TMP.GLASS.RIGHT.EXIT', 'SPOUT.RIGHT.BOS.UPSTREAM', 'TMP.GLASS.ZONE.C.E1', 'D.C.R.UL', 'TMP.GLASS.ZONE.F.E1', 'SPOUT.LEFT.BOTTOM', 'N2.TO.EA1313B', 'ROOF.HT.BAY.TOTAL.PWR.1CLBAY1', 'DROSSBOX.N2.SCN.R', 'SPOUT.LEFT.TOP', 'CASHING.BLOW.TMP', 'TMP.GLASS.ZONE.AB.E3', 'N2.TO.EA1313A.PV', 'STD.U.R'}

In [25]:
norm_process_df.head()
norm_process_df.columns = sensor_cleaned
# norm_process_df.head() # 열 중복되어도 상관없음

2. 공정명 평균으로 그룹화

In [26]:
# 중복된 열 평균으로 그룹화

seen = set()
ordered_unique_columns = []
for col in norm_process_df.columns:
    if col not in seen:
        seen.add(col)
        ordered_unique_columns.append(col)

# 2. 컬럼별 평균값 시리즈를 딕셔너리에 저장
merged_columns = {}

for col in ordered_unique_columns:
    same_cols = norm_process_df.loc[:, norm_process_df.columns == col]
    merged_columns[col] = same_cols.mean(axis=1)

# 3. 한 번에 병합
merged_df = pd.concat(merged_columns, axis=1)

# 확인
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8145 entries, 2016-01-01 07 to 2016-12-31 23
Columns: 194 entries, LIFT.OUT.ROL.MTR.M.SPD to STD.GLS.R
dtypes: float64(194)
memory usage: 12.1+ MB

3. 최종 데이터프레임 생성
- 불량률 열 결합

In [27]:
time_series_idx = df.index
time_series_idx

# 마지막 불량율 열 결합
df_defect = df.iloc[:, -14:]
# df_defect

final_df = pd.concat([merged_df, df_defect], axis= 1)
final_df.index = time_series_idx

final_df.info()
final_df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 8145 entries, 2016-01-01 07 to 2016-12-31 23
Columns: 208 entries, LIFT.OUT.ROL.MTR.M.SPD to R.Vac
dtypes: float64(202), int64(6)
memory usage: 13.0+ MB

,LIFT.OUT.ROL.MTR.M.SPD,LEHR.DRV.MTR.M.SPD,DRV.MTR.M.SPD,X,DCS.Offset.RPM.M,DAMP.POSITION.BAY.CTRL,DB.N2.SCREEN.FLOW.LEFT,DB.N2.SCREEN.FLOW.RIGHT,N2.TO.EA1313A,ROOF.HEATING.Zone,...,ROLLDOWN.폐기.RIGHT.,진공패드.폐기.RIGHT.,폐기율...,ROLLDOWN.진공패드.폐기율..LEFT.,ROLLDOWN.진공패드.폐기율..RIGHT.,ROLLDOWN.진공패드.폐기율..전체.,L.RD,L.Vac,R.RD,R.Vac
dat...date.name.,,,,,,,,,,,,,,,,,,,,,
2016-01-01 07,-1.742443,-1.699444,-1.683797,-0.755452,-1.947792,-1.251006,-1.514135,-1.529208,-0.218748,0.040366,...,8,3,11.69,8.75,14.86,11.69,0.025,0.063,0.108,0.041
2016-01-01 08,-1.744941,-1.699677,-1.685770,-0.755452,-1.947792,-1.251006,-1.514135,-1.529208,-0.218748,0.028982,...,10,0,7.19,2.17,13.33,7.19,0.000,0.022,0.133,0.000
2016-01-01 09,-1.744941,-1.699677,-1.685770,-0.755452,-1.947792,-1.251006,-1.514135,-1.529208,-0.218748,0.065345,...,0,0,3.85,7.81,0.00,3.85,0.016,0.063,0.000,0.000
2016-01-01 10,-1.744941,-1.699677,-1.685770,-0.755452,-1.947792,-1.251006,-1.514135,-1.529208,-0.218748,0.084378,...,0,0,4.96,10.29,0.00,4.96,0.000,0.103,0.000,0.000
2016-01-01 11,-1.744941,-1.699677,-1.685770,-0.755452,-1.947792,-1.251006,-1.514135,-1.529208,-0.218748,0.024016,...,0,0,0.00,0.00,0.00,0.00,0.000,0.000,0.000,0.000

In [28]:
final_df.to_csv('../data/process_extraction_mean_df.csv')

In [30]:
final_df.head()

,LIFT.OUT.ROL.MTR.M.SPD,LEHR.DRV.MTR.M.SPD,DRV.MTR.M.SPD,X,DCS.Offset.RPM.M,DAMP.POSITION.BAY.CTRL,DB.N2.SCREEN.FLOW.LEFT,DB.N2.SCREEN.FLOW.RIGHT,N2.TO.EA1313A,ROOF.HEATING.Zone,...,ROLLDOWN.폐기.RIGHT.,진공패드.폐기.RIGHT.,폐기율...,ROLLDOWN.진공패드.폐기율..LEFT.,ROLLDOWN.진공패드.폐기율..RIGHT.,ROLLDOWN.진공패드.폐기율..전체.,L.RD,L.Vac,R.RD,R.Vac
dat...date.name.,,,,,,,,,,,,,,,,,,,,,
2016-01-01 07,-1.742443,-1.699444,-1.683797,-0.755452,-1.947792,-1.251006,-1.514135,-1.529208,-0.218748,0.040366,...,8,3,11.69,8.75,14.86,11.69,0.025,0.063,0.108,0.041
2016-01-01 08,-1.744941,-1.699677,-1.685770,-0.755452,-1.947792,-1.251006,-1.514135,-1.529208,-0.218748,0.028982,...,10,0,7.19,2.17,13.33,7.19,0.000,0.022,0.133,0.000
2016-01-01 09,-1.744941,-1.699677,-1.685770,-0.755452,-1.947792,-1.251006,-1.514135,-1.529208,-0.218748,0.065345,...,0,0,3.85,7.81,0.00,3.85,0.016,0.063,0.000,0.000
2016-01-01 10,-1.744941,-1.699677,-1.685770,-0.755452,-1.947792,-1.251006,-1.514135,-1.529208,-0.218748,0.084378,...,0,0,4.96,10.29,0.00,4.96,0.000,0.103,0.000,0.000
2016-01-01 11,-1.744941,-1.699677,-1.685770,-0.755452,-1.947792,-1.251006,-1.514135,-1.529208,-0.218748,0.024016,...,0,0,0.00,0.00,0.00,0.00,0.000,0.000,0.000,0.000